apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: kubedemo-prod

patches:
  - target:
      kind: Deployment
      name: kubedemo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: Ingress
      name: kubedemo-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: kubedemo-prod.test
  - target: # NEW patch
      kind: Service
      name: kubedemo
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081