apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedemo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mallurahul/kubedemo-manifests.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true